# Load files

In [1]:
import json
import pandas as pd
import re
import numpy as np
from datetime import datetime

In [2]:
users = open('users.json')
receipts = open('receipts.json')
brands = open('brands.json')

# Correct Receipts

In [110]:
receipts = pd.read_json('receipts.json',  lines=True)

receipts.head()

,_id,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId
0,{'$oid': '5ff1e1eb0a720f0523000575'},500.0,"Receipt number 2 completed, bonus point schedu...",{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687536000},{'$date': 1609687531000},500.0,{'$date': 1609632000000},5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,26.0,5ff1e1eacfcf6c399c274ae6
1,{'$oid': '5ff1e1bb0a720f052300056b'},150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687488000},{'$date': 1609687483000},150.0,{'$date': 1609601083000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,11.0,5ff1e194b6a9d73a3a9f1052
2,{'$oid': '5ff1e1f10a720f052300057a'},5.0,All-receipts receipt bonus,{'$date': 1609687537000},{'$date': 1609687537000},NaN,{'$date': 1609687542000},NaN,5.0,{'$date': 1609632000000},1.0,"[{'needsFetchReview': False, 'partnerItemId': ...",REJECTED,10.0,5ff1e1f1cfcf6c399c274b0b
3,{'$oid': '5ff1e1ee0a7214ada100056f'},5.0,All-receipts receipt bonus,{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687539000},{'$date': 1609687534000},5.0,{'$date': 1609632000000},4.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,28.0,5ff1e1eacfcf6c399c274ae6
4,{'$oid': '5ff1e1d20a7214ada1000561'},5.0,All-receipts receipt bonus,{'$date': 1609687506000},{'$date': 1609687506000},{'$date': 1609687511000},{'$date': 1609687511000},{'$date': 1609687506000},5.0,{'$date': 1609601106000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.0,5ff1e194b6a9d73a3a9f1052

In [111]:
# id column
# for every row in column '_id', make the value as value of key->'$oid'
receipts['_id'] = receipts['_id'].apply(lambda x: x['$oid'])
receipts.head()

,_id,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId
0,5ff1e1eb0a720f0523000575,500.0,"Receipt number 2 completed, bonus point schedu...",{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687536000},{'$date': 1609687531000},500.0,{'$date': 1609632000000},5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,26.0,5ff1e1eacfcf6c399c274ae6
1,5ff1e1bb0a720f052300056b,150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687488000},{'$date': 1609687483000},150.0,{'$date': 1609601083000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,11.0,5ff1e194b6a9d73a3a9f1052
2,5ff1e1f10a720f052300057a,5.0,All-receipts receipt bonus,{'$date': 1609687537000},{'$date': 1609687537000},NaN,{'$date': 1609687542000},NaN,5.0,{'$date': 1609632000000},1.0,"[{'needsFetchReview': False, 'partnerItemId': ...",REJECTED,10.0,5ff1e1f1cfcf6c399c274b0b
3,5ff1e1ee0a7214ada100056f,5.0,All-receipts receipt bonus,{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687539000},{'$date': 1609687534000},5.0,{'$date': 1609632000000},4.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,28.0,5ff1e1eacfcf6c399c274ae6
4,5ff1e1d20a7214ada1000561,5.0,All-receipts receipt bonus,{'$date': 1609687506000},{'$date': 1609687506000},{'$date': 1609687511000},{'$date': 1609687511000},{'$date': 1609687506000},5.0,{'$date': 1609601106000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.0,5ff1e194b6a9d73a3a9f1052

In [112]:
# date columns
#
for i in receipts.columns:
    if re.findall('date', i.lower())!=[]:
        receipts[i] = receipts[i].apply(lambda x: datetime.fromtimestamp(x['$date'] // 1000) if str(x) != str(np.nan) else x)
receipts.head()

,_id,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId
0,5ff1e1eb0a720f0523000575,500.0,"Receipt number 2 completed, bonus point schedu...",2021-01-03 10:25:31,2021-01-03 10:25:31,2021-01-03 10:25:31,2021-01-03 10:25:36,2021-01-03 10:25:31,500.0,2021-01-02 19:00:00,5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,26.0,5ff1e1eacfcf6c399c274ae6
1,5ff1e1bb0a720f052300056b,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 10:24:43,2021-01-03 10:24:43,2021-01-03 10:24:43,2021-01-03 10:24:48,2021-01-03 10:24:43,150.0,2021-01-02 10:24:43,2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,11.0,5ff1e194b6a9d73a3a9f1052
2,5ff1e1f10a720f052300057a,5.0,All-receipts receipt bonus,2021-01-03 10:25:37,2021-01-03 10:25:37,NaT,2021-01-03 10:25:42,NaT,5.0,2021-01-02 19:00:00,1.0,"[{'needsFetchReview': False, 'partnerItemId': ...",REJECTED,10.0,5ff1e1f1cfcf6c399c274b0b
3,5ff1e1ee0a7214ada100056f,5.0,All-receipts receipt bonus,2021-01-03 10:25:34,2021-01-03 10:25:34,2021-01-03 10:25:34,2021-01-03 10:25:39,2021-01-03 10:25:34,5.0,2021-01-02 19:00:00,4.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,28.0,5ff1e1eacfcf6c399c274ae6
4,5ff1e1d20a7214ada1000561,5.0,All-receipts receipt bonus,2021-01-03 10:25:06,2021-01-03 10:25:06,2021-01-03 10:25:11,2021-01-03 10:25:11,2021-01-03 10:25:06,5.0,2021-01-02 10:25:06,2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.0,5ff1e194b6a9d73a3a9f1052

In [114]:
# check any duplicates in '_id'
receipts[receipts.duplicated(subset = '_id', keep = False)]

Empty DataFrame
Columns: [_id, bonusPointsEarned, bonusPointsEarnedReason, createDate, dateScanned, finishedDate, modifyDate, pointsAwardedDate, pointsEarned, purchaseDate, purchasedItemCount, rewardsReceiptItemList, rewardsReceiptStatus, totalSpent, userId]
Index: []

In [115]:
#check any null value in '_id'
receipts['_id'].isnull().any()

False

In [122]:
# check if createDate == dateScanned
receipts['createDate'].equals(receipts['dateScanned'])

True

In [134]:
# check if bonusPointsEarned == pointsEarned
receipts['bonusPointsEarned'].equals(receipts['pointsEarned'])

False

## Deal with rewardsReceiptItemList Column

In [116]:
# get all keys in rewardsReceiptItemList column

RRIL_keys = []

for i in receipts[~receipts.rewardsReceiptItemList.isnull()].rewardsReceiptItemList:
    RRIL_keys.extend(i[0].keys())
    
# delete duplicated keys    
RRIL_keys = list(set(RRIL_keys))
print(RRIL_keys)

['brandCode', 'rewardsGroup', 'userFlaggedBarcode', 'originalMetaBriteDescription', 'userFlaggedQuantity', 'rewardsProductPartnerId', 'userFlaggedPrice', 'metabriteCampaignId', 'quantityPurchased', 'needsFetchReview', 'preventTargetGapPoints', 'discountedItemPrice', 'targetPrice', 'description', 'competitorRewardsGroup', 'originalMetaBriteBarcode', 'itemPrice', 'barcode', 'originalMetaBriteQuantityPurchased', 'pointsEarned', 'pointsPayerId', 'pointsNotAwardedReason', 'userFlaggedDescription', 'originalReceiptItemText', 'needsFetchReviewReason', 'priceAfterCoupon', 'finalPrice', 'itemNumber', 'competitiveProduct', 'userFlaggedNewItem', 'deleted', 'partnerItemId']

In [117]:
# create a new table for rewardsReceiptItemList
RRIL = pd.DataFrame(columns=['_id'] + RRIL_keys)

for i in range(receipts.shape[0]):
    if isinstance(receipts.rewardsReceiptItemList[i], list):
        receipts.rewardsReceiptItemList[i][0]['_id'] = receipts._id[i]

In [118]:
for i in range(receipts.shape[0]):
    if isinstance(receipts.rewardsReceiptItemList[i], list):
        tempt = pd.DataFrame(receipts.rewardsReceiptItemList[i][0], index=[0])
        RRIL = RRIL.append(tempt, sort=False).reset_index(drop=True)

In [119]:
RRIL.head()

,_id,brandCode,rewardsGroup,userFlaggedBarcode,originalMetaBriteDescription,userFlaggedQuantity,rewardsProductPartnerId,userFlaggedPrice,metabriteCampaignId,quantityPurchased,...,userFlaggedDescription,originalReceiptItemText,needsFetchReviewReason,priceAfterCoupon,finalPrice,itemNumber,competitiveProduct,userFlaggedNewItem,deleted,partnerItemId
0,5ff1e1eb0a720f0523000575,NaN,NaN,4011,NaN,5,NaN,26.00,NaN,5,...,NaN,NaN,NaN,NaN,26.00,NaN,NaN,True,NaN,1
1,5ff1e1bb0a720f052300056b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1
2,5ff1e1f10a720f052300057a,NaN,NaN,4011,NaN,3,NaN,26.00,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,NaN,1
3,5ff1e1ee0a7214ada100056f,NaN,NaN,4011,NaN,4,NaN,28.00,NaN,4,...,NaN,NaN,NaN,NaN,28.00,NaN,NaN,True,NaN,1
4,5ff1e1d20a7214ada1000561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1

In [121]:
# check any duplicates
print(RRIL[RRIL.duplicated(subset = '_id', keep = False)])

#check any null value in '_id'
print(RRIL['_id'].isnull().any())

Empty DataFrame
Columns: [_id, brandCode, rewardsGroup, userFlaggedBarcode, originalMetaBriteDescription, userFlaggedQuantity, rewardsProductPartnerId, userFlaggedPrice, metabriteCampaignId, quantityPurchased, needsFetchReview, preventTargetGapPoints, discountedItemPrice, targetPrice, description, competitorRewardsGroup, originalMetaBriteBarcode, itemPrice, barcode, originalMetaBriteQuantityPurchased, pointsEarned, pointsPayerId, pointsNotAwardedReason, userFlaggedDescription, originalReceiptItemText, needsFetchReviewReason, priceAfterCoupon, finalPrice, itemNumber, competitiveProduct, userFlaggedNewItem, deleted, partnerItemId]
Index: []

[0 rows x 33 columns]
False

In [123]:
# delete rewardsReceiptItemList column from receipts table
del receipts['rewardsReceiptItemList']
receipts.head()

,_id,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptStatus,totalSpent,userId
0,5ff1e1eb0a720f0523000575,500.0,"Receipt number 2 completed, bonus point schedu...",2021-01-03 10:25:31,2021-01-03 10:25:31,2021-01-03 10:25:31,2021-01-03 10:25:36,2021-01-03 10:25:31,500.0,2021-01-02 19:00:00,5.0,FINISHED,26.0,5ff1e1eacfcf6c399c274ae6
1,5ff1e1bb0a720f052300056b,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 10:24:43,2021-01-03 10:24:43,2021-01-03 10:24:43,2021-01-03 10:24:48,2021-01-03 10:24:43,150.0,2021-01-02 10:24:43,2.0,FINISHED,11.0,5ff1e194b6a9d73a3a9f1052
2,5ff1e1f10a720f052300057a,5.0,All-receipts receipt bonus,2021-01-03 10:25:37,2021-01-03 10:25:37,NaT,2021-01-03 10:25:42,NaT,5.0,2021-01-02 19:00:00,1.0,REJECTED,10.0,5ff1e1f1cfcf6c399c274b0b
3,5ff1e1ee0a7214ada100056f,5.0,All-receipts receipt bonus,2021-01-03 10:25:34,2021-01-03 10:25:34,2021-01-03 10:25:34,2021-01-03 10:25:39,2021-01-03 10:25:34,5.0,2021-01-02 19:00:00,4.0,FINISHED,28.0,5ff1e1eacfcf6c399c274ae6
4,5ff1e1d20a7214ada1000561,5.0,All-receipts receipt bonus,2021-01-03 10:25:06,2021-01-03 10:25:06,2021-01-03 10:25:11,2021-01-03 10:25:11,2021-01-03 10:25:06,5.0,2021-01-02 10:25:06,2.0,FINISHED,1.0,5ff1e194b6a9d73a3a9f1052

# Correct brands

In [125]:
brands = pd.read_json('brands.json',  lines=True)

brands.head()

,_id,barcode,category,categoryCode,cpg,name,topBrand,brandCode
0,{'$oid': '601ac115be37ce2ead437551'},511111019862,Baking,BAKING,"{'$id': {'$oid': '601ac114be37ce2ead437550'}, ...",test brand @1612366101024,0.0,NaN
1,{'$oid': '601c5460be37ce2ead43755f'},511111519928,Beverages,BEVERAGES,"{'$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}, ...",Starbucks,0.0,STARBUCKS
2,{'$oid': '601ac142be37ce2ead43755d'},511111819905,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146176,0.0,TEST BRANDCODE @1612366146176
3,{'$oid': '601ac142be37ce2ead43755a'},511111519874,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146051,0.0,TEST BRANDCODE @1612366146051
4,{'$oid': '601ac142be37ce2ead43755e'},511111319917,Candy & Sweets,CANDY_AND_SWEETS,"{'$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}, ...",test brand @1612366146827,0.0,TEST BRANDCODE @1612366146827

In [126]:
# id column
# for every row in column '_id', make the value as value of key->'$oid'
brands['_id'] = brands['_id'].apply(lambda x: x['$oid'])
brands.head()

,_id,barcode,category,categoryCode,cpg,name,topBrand,brandCode
0,601ac115be37ce2ead437551,511111019862,Baking,BAKING,"{'$id': {'$oid': '601ac114be37ce2ead437550'}, ...",test brand @1612366101024,0.0,NaN
1,601c5460be37ce2ead43755f,511111519928,Beverages,BEVERAGES,"{'$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}, ...",Starbucks,0.0,STARBUCKS
2,601ac142be37ce2ead43755d,511111819905,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146176,0.0,TEST BRANDCODE @1612366146176
3,601ac142be37ce2ead43755a,511111519874,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146051,0.0,TEST BRANDCODE @1612366146051
4,601ac142be37ce2ead43755e,511111319917,Candy & Sweets,CANDY_AND_SWEETS,"{'$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}, ...",test brand @1612366146827,0.0,TEST BRANDCODE @1612366146827

In [127]:
# cpg column

# check cpg column
for i in brands[~brands.cpg.isnull()].cpg:
    print(i)

{'$id': {'$oid': '601ac114be37ce2ead437550'}, '$ref': 'Cogs'}
{'$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}, '$ref': 'Cogs'}
{'$id': {'$oid': '601ac142be37ce2ead437559'}, '$ref': 'Cogs'}
{'$id': {'$oid': '601ac142be37ce2ead437559'}, '$ref': 'Cogs'}
{'$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}, '$ref': 'Cogs'}
{'$id': {'$oid': '601ac142be37ce2ead437559'}, '$ref': 'Cogs'}
{'$id': {'$oid': '601ac142be37ce2ead437559'}, '$ref': 'Cogs'}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '59ba6f1ce4b092b29c167346'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f4bf556be37ce0b44915549'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b03c9a25efd0aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda2c6225a284aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f358338be37ce443bf9d557'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fb28549be37ce522e165cb4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '55b62995e4b0d8e685c14213'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda2c6225a284aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cpgs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5e9f12f5be37ce3e45b6a77e'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f493e72be37ce64d0ae36c2'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f4936dcbe37ce52f8314fd8'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd2a0aebe37ce49eb72c0ed'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f494c5d04db711dd8fe87e2'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f35a0babe37ce6853cff1fd'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd29590be37ce38bbbefb25'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd3acb5be37ce0d9386bb3e'}}
{'$ref': 'Cogs', '$id': {'$oid': '550b2565e4b001d5e9e4146f'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fa1c567be37ce402c4618ef'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '55b62995e4b0d8e685c14213'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f16f535be37ce2b30061e24'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f6ede4b03c9a25efd0e6'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b03c9a25efd0aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f3d6f44be37ce4ddbb1bb3a'}}
{'$ref': 'Cogs', '$id': {'$oid': '5c76d20595144c5375687b4e'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '55b62995e4b0d8e685c14213'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f3ff222be37ce1c81aa1e0c'}}
{'$ref': 'Cogs', '$id': {'$oid': '5c76d20595144c5375687b4e'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f3e9195be37ce5a0e01b95f'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fb6b608be37ce522e165cb9'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd3acb5be37ce0d9386bb3e'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda2c6225a284aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fb2852cbe37ce522e165cae'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b03c9a25efd0aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fa98944be37ce239d1070ff'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f493682be37ce52f8314fcb'}}
{'$ref': 'Cpgs', '$id': {'$oid': '57ace90fe4b057c992a316ab'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ac'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fc54c0abe37ce1911dbb3b1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f358338be37ce443bf9d557'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b03c9a25efd0aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f9770bfbe37ce03d08a2d83'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f513e9ebe37ce21f1287bff'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f3e9172be37ce5a0e01b952'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f4936ddbe37ce52f8314fda'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f43faabbe37ce3ef3fd3714'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fa98944be37ce239d1070fd'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b03c9a25efd0aa'}}
{'$ref': 'Cpgs', '$id': {'$oid': '55a41b4be4b0d0a65b3692ee'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cpgs', '$id': {'$oid': '55b62995e4b0d8e685c14213'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f43faabbe37ce3ef3fd3714'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda2c6225a284aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5e28b81cee7f2d697e835bcd'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f494c5d04db711dd8fe87e2'}}
{'$ref': 'Cogs', '$id': {'$oid': '550b2565e4b001d5e9e4146f'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fb2852cbe37ce522e165cae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '55b62995e4b0d8e685c14213'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b03c9a25efd0aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fcda494be37ce688e08b0cb'}}
{'$ref': 'Cogs', '$id': {'$oid': '5eebc5412455c97a877ef382'}}
{'$ref': 'Cogs', '$id': {'$oid': '55b62995e4b0d8e685c14213'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '5e28b81cee7f2d697e835bcd'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b03c9a25efd0aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5c45f8b087ff3552f950f026'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '55b62995e4b0d8e685c14213'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fcda494be37ce688e08b0cb'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f3ff222be37ce1c81aa1e0c'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f772951be37ce6b592e90d1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fa1c568be37ce402c4618f5'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fb6b608be37ce522e165cb9'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5e28b81cee7f2d697e835bcd'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f16f535be37ce2b30061e24'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f7ba644be37ce23081c5289'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b03c9a25efd0aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f504acabe37ce0b793c9417'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7ffe4b03c9a25efd16b'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe3a87be37ce7aab2d4fda'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe3a85be37ce7aab2d4fd4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fff3a7abe37ce2bb793010d'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe3a85be37ce7aab2d4fd4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe3a85be37ce7aab2d4fd4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe35eabe37ce5e01754c45'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe347ebe37ce5e01754c3d'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe35eabe37ce5e01754c45'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f493e72be37ce64d0ae36c2'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fb6b608be37ce522e165cb9'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f494c5d04db711dd8fe87e2'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f772951be37ce6b592e90cf'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f504ac2be37ce0b793c9411'}}
{'$ref': 'Cogs', '$id': {'$oid': '550b2565e4b001d5e9e4146f'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd2a0bfbe37ce49eb72c0ef'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f99f71bbe37ce13da9eade6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe3681be37ce5e01754c54'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe347ebe37ce5e01754c3d'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe347ebe37ce5e01754c3d'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe3480be37ce5e01754c43'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe35eabe37ce5e01754c45'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe35f9be37ce5e01754c4b'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe35eabe37ce5e01754c45'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff768e3be37ce1e961f329f'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff768d4be37ce1e961f3299'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff768d4be37ce1e961f3299'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff768d4be37ce1e961f3299'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff77857be37ce58ce500839'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd7f2b3be37ce7339755868'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd7f2b3be37ce7339755868'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd7f2b3be37ce7339755868'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd7f2b8be37ce733975586e'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd3acb5be37ce0d9386bb3e'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cpgs', '$id': {'$oid': '581ce8d5e4b058c71f74c442'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b03c9a25efd0aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f3d6f44be37ce4ddbb1bb3a'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f628235be37ce78e6e2efb0'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f3ff200be37ce1c81aa1e0a'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f493665be37ce52f8314fc9'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5c4f20b01b4181298aacffc1'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda2c6225a284aa'}}
{'$id': {'$oid': '5fb6d381be37ce522e165cbd'}, '$ref': 'Cogs'}
{'$id': {'$oid': '5fb6d381be37ce522e165cbd'}, '$ref': 'Cogs'}
{'$id': {'$oid': '5fb6d381be37ce522e165cbd'}, '$ref': 'Cogs'}
{'$id': {'$oid': '5fb6d381be37ce522e165cbd'}, '$ref': 'Cogs'}
{'$id': {'$oid': '5fb6d381be37ce522e165cbd'}, '$ref': 'Cogs'}
{'$id': {'$oid': '5fb6d381be37ce522e165cbd'}, '$ref': 'Cogs'}
{'$id': {'$oid': '5fb6d381be37ce522e165cbd'}, '$ref': 'Cogs'}
{'$id': {'$oid': '5fb6d381be37ce522e165cbd'}, '$ref': 'Cogs'}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f3d6f44be37ce4ddbb1bb3a'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fa1c567be37ce402c4618ef'}}
{'$ref': 'Cpgs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fcda47cbe37ce688e08b0c2'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fb6b608be37ce522e165cb9'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5459429be4b0bfcb1e864082'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda2c6225a284aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f513ea0be37ce21f1287c01'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cpgs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '59b96571e4b0bf7c7980588b'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda2c6225a284aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5459429be4b0bfcb1e864082'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b03c9a25efd0aa'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fa98944be37ce239d1070ff'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f9770bfbe37ce03d08a2d83'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f58fa84be37ce21f1287c0f'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda2c6225a284aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff78071be37ce6a424ca0e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff78071be37ce6a424ca0e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff78071be37ce6a424ca0e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff78071be37ce6a424ca0e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff789c5be37ce786ba0f6a2'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff77857be37ce58ce500839'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff77857be37ce58ce500839'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff78070be37ce6a424ca0e5'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff77857be37ce58ce500839'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff77859be37ce58ce50083f'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '550b2565e4b001d5e9e4146f'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fdce9e9be37ce5fa8ba59d6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fdce9e9be37ce5fa8ba59d6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fdce9e9be37ce5fa8ba59d6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fdce9e9be37ce5fa8ba59d6'}}

{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff75cdebe37ce1e961f328c'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff75cdebe37ce1e961f328c'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff75cdebe37ce1e961f328c'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f504ac2be37ce0b793c9411'}}
{'$ref': 'Cogs', '$id': {'$oid': '5e5ea9cc9c50da1291a6d074'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fcff304be37ce6d53dfc683'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f35a0bcbe37ce6853cff20a'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fb6b608be37ce522e165cb9'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff75cdebe37ce1e961f328c'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff768d4be37ce1e961f3299'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda2c6225a284aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd3ae1fbe37ce0d9386bb54'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd3ae1fbe37ce0d9386bb54'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd3ae1fbe37ce0d9386bb54'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd3ae20be37ce0d9386bb5a'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fff3aa0be37ce2bb7930116'}}
{'$ref': 'Cogs', '$id': {'$oid': '6000a0c6be37ce2bb793011c'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fff3aa0be37ce2bb7930116'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fff3aa0be37ce2bb7930116'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fff3aa0be37ce2bb7930116'}}
{'$ref': 'Cogs', '$id': {'$oid': '6000b8c3be37ce321363c6bf'}}
{'$ref': 'Cogs', '$id': {'$oid': '6000b8c3be37ce321363c6bf'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '60019b82be37ce4f17e558d1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5459429be4b0bfcb1e864082'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fb6b608be37ce522e165cb9'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fcda494be37ce688e08b0cb'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f19e054be37ce33f74a166e'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f493dabbe37ce64d0ae36ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd29590be37ce38bbbefb25'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f493d85be37ce64d0ae36b1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff3842abe37ce2c56dacbab'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff3842bbe37ce2c56dacbad'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda2c6225a284aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '6000b8c3be37ce321363c6bf'}}
{'$ref': 'Cogs', '$id': {'$oid': '6000b8c4be37ce321363c6c5'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff3842bbe37ce2c56dacbad'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff3842bbe37ce2c56dacbad'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff3842bbe37ce2c56dacbad'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff73cf9be37ce1e961f3256'}}
{'$ref': 'Cogs', '$id': {'$oid': '60019b82be37ce4f17e558d1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '60074260be37ce360be639f5'}}
{'$ref': 'Cogs', '$id': {'$oid': '60019b82be37ce4f17e558d1'}}
{'$ref': 'Cogs', '$id': {'$oid': '60019b83be37ce4f17e558d7'}}
{'$ref': 'Cogs', '$id': {'$oid': '60019b82be37ce4f17e558d1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff8b5febe37ce4a13986613'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe2df8be37ce5e01754c1f'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe2e38be37ce5e01754c21'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff8b5fbbe37ce4a1398660d'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe2ce0be37ce5e01754c16'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff8b5fbbe37ce4a1398660d'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff8b5fbbe37ce4a1398660d'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe2ca0be37ce5e01754c09'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe2ca0be37ce5e01754c09'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe2ca0be37ce5e01754c09'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ffe2ca0be37ce5e01754c09'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff789d5be37ce786ba0f6a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff789c5be37ce786ba0f6a2'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff8b5fbbe37ce4a1398660d'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff789c5be37ce786ba0f6a2'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ff789c5be37ce786ba0f6a2'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f441280be37ce5dbe9b7c7d'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f493dabbe37ce64d0ae36ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f712e4b03c9a25efd0f9'}}
{'$ref': 'Cpgs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f7ba678be37ce23081c5296'}}
{'$ref': 'Cogs', '$id': {'$oid': '5c6d516795144c607914426e'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b03c9a25efd0aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f99f720be37ce13da9eadec'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f872bd3be37ce66db5dd982'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '5ea07defbe37ce3e45b6a780'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f99f71bbe37ce13da9eade6'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f7ba644be37ce23081c5289'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f403232be37ce5f78d9ed1a'}}
{'$id': {'$oid': '5fb6d381be37ce522e165cbd'}, '$ref': 'Cogs'}
{'$id': {'$oid': '5fb6d381be37ce522e165cbd'}, '$ref': 'Cogs'}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd2a0bfbe37ce49eb72c0ef'}}
{'$ref': 'Cpgs', '$id': {'$oid': '53501d2ab9237fd7718f9e1a'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda2c6225a284aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '550b2565e4b001d5e9e4146f'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f5bc4f1be37ce17125ac0e6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fc54c0abe37ce1911dbb3b1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f4a7a5bbe37ce2d95e65c9f'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f4a64e7be37ce17d23b3178'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5e28b81cee7f2d697e835bcd'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d9b4f591dda2c6225a284aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cpgs', '$id': {'$oid': '55b62995e4b0d8e685c14213'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fc54c0abe37ce1911dbb3b1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5e5ea9cc9c50da1291a6d074'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fa98944be37ce239d1070ff'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5c45f8b087ff3552f950f026'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '55b62995e4b0d8e685c14213'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f4a7a5bbe37ce2d95e65c9f'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5c6c2ee995144c6db8fe1976'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f403231be37ce5f78d9ed14'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '56462469e4b0c05761111936'}}
{'$ref': 'Cogs', '$id': {'$oid': '60074277be37ce360be639fe'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fa1c567be37ce402c4618ef'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '55b62995e4b0d8e685c14213'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f513ea0be37ce21f1287c01'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5e28b81cee7f2d697e835bcd'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fcff304be37ce6d53dfc683'}}
{'$ref': 'Cogs', '$id': {'$oid': '5e28b81cee7f2d697e835bcd'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f9770c0be37ce03d08a2d89'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f493682be37ce52f8314fcb'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7ffe4b03c9a25efd16b'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fda3711be37ce09e351596d'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd7f2b3be37ce7339755868'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fb6b608be37ce522e165cb9'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '550b2565e4b001d5e9e4146f'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f7760f0be37ce1d26d7b7a2'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f7ba914be37ce2f290fb24f'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fb6b608be37ce522e165cb9'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f7ba932be37ce2f290fb251'}}
{'$ref': 'Cogs', '$id': {'$oid': '550b2565e4b001d5e9e4146f'}}
{'$ref': 'Cogs', '$id': {'$oid': '550b2565e4b001d5e9e4146f'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd2a0bfbe37ce49eb72c0ef'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332fa58e4b03c9a25efd215'}}
{'$ref': 'Cogs', '$id': {'$oid': '5459429be4b0bfcb1e864082'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$id': {'$oid': '5fb6d381be37ce522e165cbd'}, '$ref': 'Cogs'}
{'$id': {'$oid': '5fb6d381be37ce522e165cbd'}, '$ref': 'Cogs'}
{'$id': {'$oid': '5fb6d381be37ce522e165cbd'}, '$ref': 'Cogs'}
{'$ref': 'Cogs', '$id': {'$oid': '550b2565e4b001d5e9e4146f'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fb6b608be37ce522e165cb9'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f77274bbe37ce6b592e90b9'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f4a7a5bbe37ce2d95e65c9f'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f628214be37ce78e6e2efaa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f441280be37ce5dbe9b7c7d'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fd29590be37ce38bbbefb25'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b03c9a25efd0aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fcda494be37ce688e08b0cb'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f4bf53dbe37ce0b44915540'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5f2e4b03c9a25efd0aa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f43faabbe37ce3ef3fd3714'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f513ea0be37ce21f1287c01'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fb6b608be37ce522e165cb9'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '60074277be37ce360be639fe'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f872b7fbe37ce66db5dd975'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f208daebe37ce7958c59520'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '550b2565e4b001d5e9e4146f'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '53e10d6368abd3c7065097cc'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5a734034e4b0d58f376be874'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f10c05cbe37ce238c6cabaf'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f7a7e4b03c9a25efd134'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f5bc4f1be37ce17125ac0e8'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f3e4b03c9a25efd0ae'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5f6e4b03c9a25efd0b4'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '5d5d4fd16d5f3b23d1bc7905'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f3e9172be37ce5a0e01b952'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5fb6b608be37ce522e165cb9'}}
{'$ref': 'Cpgs', '$id': {'$oid': '5332f5ebe4b03c9a25efd0a8'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f628214be37ce78e6e2efaa'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}}
{'$ref': 'Cogs', '$id': {'$oid': '559c2234e4b06aca36af13c6'}}
{'$ref': 'Cogs', '$id': {'$oid': '5332f709e4b03c9a25efd0f1'}}
{'$ref': 'Cogs', '$id': {'$oid': '5f77274dbe37ce6b592e90bf'}}

In [128]:
# break cpg column to cpg_id column & cpg_ref column
brands['cpg_id'] = brands['cpg'].apply(lambda x: x['$id']['$oid'])
brands['cpg_ref'] = brands['cpg'].apply(lambda x: x['$ref'])
del brands['cpg']
brands.head()

,_id,barcode,category,categoryCode,name,topBrand,brandCode,cpg_id,cpg_ref
0,601ac115be37ce2ead437551,511111019862,Baking,BAKING,test brand @1612366101024,0.0,NaN,601ac114be37ce2ead437550,Cogs
1,601c5460be37ce2ead43755f,511111519928,Beverages,BEVERAGES,Starbucks,0.0,STARBUCKS,5332f5fbe4b03c9a25efd0ba,Cogs
2,601ac142be37ce2ead43755d,511111819905,Baking,BAKING,test brand @1612366146176,0.0,TEST BRANDCODE @1612366146176,601ac142be37ce2ead437559,Cogs
3,601ac142be37ce2ead43755a,511111519874,Baking,BAKING,test brand @1612366146051,0.0,TEST BRANDCODE @1612366146051,601ac142be37ce2ead437559,Cogs
4,601ac142be37ce2ead43755e,511111319917,Candy & Sweets,CANDY_AND_SWEETS,test brand @1612366146827,0.0,TEST BRANDCODE @1612366146827,5332fa12e4b03c9a25efd1e7,Cogs

In [129]:
# check any duplicates
print(brands[brands.duplicated(subset = '_id', keep = False)])

#check any null value in '_id'
print(brands['_id'].isnull().any())

Empty DataFrame
Columns: [_id, barcode, category, categoryCode, name, topBrand, brandCode, cpg_id, cpg_ref]
Index: []
False

# Correct users

In [137]:
users = pd.read_json('users.json',  lines=True)

users.head()

,_id,active,createdDate,lastLogin,role,signUpSource,state
0,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
1,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
2,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
3,{'$oid': '5ff1e1eacfcf6c399c274ae6'},True,{'$date': 1609687530554},{'$date': 1609687530597},consumer,Email,WI
4,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI

In [138]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495 entries, 0 to 494
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   _id           495 non-null    object
 1   active        495 non-null    bool
 2   createdDate   495 non-null    object
 3   lastLogin     433 non-null    object
 4   role          495 non-null    object
 5   signUpSource  447 non-null    object
 6   state         439 non-null    object
dtypes: bool(1), object(6)
memory usage: 23.8+ KB

In [139]:
# id column
users['_id'] = users['_id'].apply(lambda x: x['$oid'])

# date columns
users['createdDate'] = users['createdDate'].apply(lambda x:datetime.fromtimestamp(x['$date'] // 1000) if str(x) != str(np.nan) else x)
users['lastLogin'] = users['lastLogin'].apply(lambda x:datetime.fromtimestamp(x['$date'] // 1000) if str(x) != str(np.nan) else x)

users.head()

,_id,active,createdDate,lastLogin,role,signUpSource,state
0,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 10:24:04,2021-01-03 10:25:37,consumer,Email,WI
1,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 10:24:04,2021-01-03 10:25:37,consumer,Email,WI
2,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 10:24:04,2021-01-03 10:25:37,consumer,Email,WI
3,5ff1e1eacfcf6c399c274ae6,True,2021-01-03 10:25:30,2021-01-03 10:25:30,consumer,Email,WI
4,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 10:24:04,2021-01-03 10:25:37,consumer,Email,WI

In [140]:
# check any duplicates
print(users[users.duplicated(subset = '_id', keep = False)])

                          _id  active         createdDate           lastLogin  \
0    5ff1e194b6a9d73a3a9f1052    True 2021-01-03 10:24:04 2021-01-03 10:25:37
1    5ff1e194b6a9d73a3a9f1052    True 2021-01-03 10:24:04 2021-01-03 10:25:37
2    5ff1e194b6a9d73a3a9f1052    True 2021-01-03 10:24:04 2021-01-03 10:25:37
3    5ff1e1eacfcf6c399c274ae6    True 2021-01-03 10:25:30 2021-01-03 10:25:30
4    5ff1e194b6a9d73a3a9f1052    True 2021-01-03 10:24:04 2021-01-03 10:25:37
..                        ...     ...                 ...                 ...
490  54943462e4b07e684157a532    True 2014-12-19 09:21:22 2021-03-05 11:52:23
491  54943462e4b07e684157a532    True 2014-12-19 09:21:22 2021-03-05 11:52:23
492  54943462e4b07e684157a532    True 2014-12-19 09:21:22 2021-03-05 11:52:23
493  54943462e4b07e684157a532    True 2014-12-19 09:21:22 2021-03-05 11:52:23
494  54943462e4b07e684157a532    True 2014-12-19 09:21:22 2021-03-05 11:52:23

            role signUpSource state
0       consumer        Email    WI
1       consumer        Email    WI
2       consumer        Email    WI
3       consumer        Email    WI
4       consumer        Email    WI
..           ...          ...   ...
490  fetch-staff          NaN   NaN
491  fetch-staff          NaN   NaN
492  fetch-staff          NaN   NaN
493  fetch-staff          NaN   NaN
494  fetch-staff          NaN   NaN

[353 rows x 7 columns]

In [141]:
# delete duplicated records
users = users.drop_duplicates()
users.head()

,_id,active,createdDate,lastLogin,role,signUpSource,state
0,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 10:24:04,2021-01-03 10:25:37,consumer,Email,WI
3,5ff1e1eacfcf6c399c274ae6,True,2021-01-03 10:25:30,2021-01-03 10:25:30,consumer,Email,WI
6,5ff1e1e8cfcf6c399c274ad9,True,2021-01-03 10:25:28,2021-01-03 10:25:28,consumer,Email,WI
7,5ff1e1b7cfcf6c399c274a5a,True,2021-01-03 10:24:39,2021-01-03 10:24:39,consumer,Email,WI
9,5ff1e1f1cfcf6c399c274b0b,True,2021-01-03 10:25:37,2021-01-03 10:25:37,consumer,Email,WI

In [67]:
#receipts.to_csv('./new_receipts.csv', index=False)
#RRIL.to_csv('./RRIL.csv', index=False)
#users.to_csv('./new_users.csv', index=False)
#brands.to_csv('./new_brands.csv', index=False)

# Task 2 Business Queries

In [38]:
from sqlalchemy import create_engine
engine = create_engine('sqlite://', echo=False)

In [39]:
receipts.drop_duplicates(subset=['_id']).to_sql('receipts',con=engine)

In [40]:
brands.drop_duplicates(subset=['_id']).to_sql('brands',con=engine)

In [41]:
users.drop_duplicates(subset=['_id']).to_sql('users',con=engine)

In [42]:
RRIL.drop_duplicates(subset=['_id']).to_sql('RRIL',con=engine)

## 1. Top 5 brands by receipts scanned for most recent month?

In [89]:
# Calculate top5 brands for the latest month
engine.execute("WITH etc AS (\
                    SELECT \
                        strftime('%Y%m',datetime(re.dateScanned)) AS dateScanned, \
                        RRIL.brandCode, COUNT(re._id) AS cnt, \
                        ROW_NUMBER() OVER (PARTITION BY strftime('%Y%m',datetime(re.dateScanned)) ORDER BY COUNT(re._id) DESC) AS receipts_rnk, \
                        DENSE_RANK() OVER (ORDER BY strftime('%Y%m',datetime(re.dateScanned)) DESC) AS dateScanned_rnk \
                    FROM receipts re \
                    LEFT JOIN RRIL \
                    ON re._id=RRIL._id \
                    WHERE RRIL.brandCode IS NOT NULL \
                    GROUP BY \
                        strftime('%Y%m',datetime(re.dateScanned)), \
                        RRIL.brandCode \
                    ORDER BY \
                       strftime('%Y%m',datetime(re.dateScanned)) DESC, \
                       receipts_rnk) \
               SELECT *\
               FROM etc \
               WHERE receipts_rnk <= 5 AND dateScanned_rnk = 1\
               ORDER BY cnt DESC;").fetchall()

[('202102', 'BRAND', 3, 1, 1), ('202102', 'MISSION', 2, 2, 1)]

For the most recent month, only two brands have records, so only 2 bands in Top5: 'BRAND' and 'MISSION'.

## 2. How does the ranking of the top 5 brands by receipts scanned for the recent month compare to the ranking for the previous month?

In [90]:
# Calculate top5 brands for the 2nd latest month
engine.execute("WITH etc AS (\
                    SELECT \
                        strftime('%Y%m',datetime(re.dateScanned)) AS dateScanned, \
                        RRIL.brandCode, COUNT(re._id) AS cnt, \
                        ROW_NUMBER() OVER (PARTITION BY strftime('%Y%m',datetime(re.dateScanned)) ORDER BY COUNT(re._id) DESC) AS receipts_rnk, \
                        DENSE_RANK() OVER (ORDER BY strftime('%Y%m',datetime(re.dateScanned)) DESC) AS dateScanned_rnk \
                    FROM receipts re \
                    LEFT JOIN RRIL \
                    ON re._id=RRIL._id \
                    WHERE RRIL.brandCode IS NOT NULL \
                    GROUP BY \
                        strftime('%Y%m',datetime(re.dateScanned)), \
                        RRIL.brandCode \
                    ORDER BY \
                       strftime('%Y%m',datetime(re.dateScanned)) DESC, \
                       receipts_rnk) \
               SELECT *\
               FROM etc \
               WHERE receipts_rnk <= 5 AND dateScanned_rnk = 2\
               ORDER BY cnt DESC;").fetchall()

[('202101', 'BRAND', 19, 1, 2),
 ('202101', 'HY-VEE', 8, 2, 2),
 ('202101', 'BEN AND JERRYS', 8, 3, 2),
 ('202101', 'WINGSTOP', 7, 4, 2),
 ('202101', 'MISSION', 5, 5, 2)]

For the previous month, Top5 brands are:
    1.'BRAND' 2.'HY-VEE' 3.'BEN AND JERRYS' 4.'WINGSTOP' 5.'MISSION'

## 3. When considering average spend from receipts with 'rewardsReceiptStatus' of 'Accepted' or 'Rejected', which is greater?

In [92]:
engine.execute("SELECT\
                    rewardsReceiptStatus \
                FROM (SELECT \
                            DISTINCT rewardsReceiptStatus, \
                            RANK() OVER (PARTITION BY rewardsReceiptStatus ORDER BY AVG(totalSpent) DESC) AS rnk \
                      FROM receipts \
                      WHERE rewardsReceiptStatus IN ('FINISHED','REJECTED')) \
                WHERE rnk = 1;").fetchall()

[('FINISHED',)]

Receipts with status of finished are greater.

## 4. When considering total number of items purchased from receipts with 'rewardsReceiptStatus’ of ‘Accepted’ or ‘Rejected’, which is greater?

In [93]:
engine.execute("SELECT\
                    rewardsReceiptStatus \
                FROM (SELECT \
                            DISTINCT rewardsReceiptStatus, \
                            RANK() OVER (PARTITION BY rewardsReceiptStatus ORDER BY SUM(purchasedItemCount) DESC) AS rnk \
                      FROM receipts \
                      WHERE rewardsReceiptStatus IN ('FINISHED','REJECTED')) \
                WHERE rnk = 1;").fetchall()

[('FINISHED',)]

Still receipts with status of finished are greater.

## 5. Which Brand has the most spend among users who were created within the past 6 months?

In [105]:
engine.execute("SELECT RRIL.brandCode, SUM(r.totalSpent)\
                FROM RRIL \
                LEFT JOIN receipts r   \
                ON RRIL._id = r._id \
                LEFT JOIN users u\
                ON r.userId = u._id \
                WHERE u._id in (SELECT _id \
                                FROM USERS \
                                WHERE date(datetime(createdDate/1000,'unixepoch')) \
                                > (select date(max(datetime(createdDate/1000,'unixepoch')), '-6 months') FROM USERS )\
                                ) \
                      AND RRIL.brandCode IS NOT NULL \
                GROUP BY RRIL.brandCode \
                ORDER BY SUM(r.totalSpent) DESC LIMIT 1").fetchall()

[('BETTY CROCKER', 11175.57)]

BETTY CROCKER

## 6. Which brand has the most transactions among users who were created within the past 6 months?

In [106]:
engine.execute("SELECT RRIL.brandCode, COUNT(*)\
                FROM RRIL \
                LEFT JOIN receipts r   \
                ON RRIL._id = r._id \
                LEFT JOIN users u\
                ON r.userId = u._id \
                WHERE u._id in (SELECT _id \
                                FROM USERS \
                                WHERE date(datetime(createdDate/1000,'unixepoch')) \
                                > (select date(max(datetime(createdDate/1000,'unixepoch')), '-6 months') FROM USERS )\
                                ) \
                      AND RRIL.brandCode IS NOT NULL \
                GROUP BY RRIL.brandCode \
                ORDER BY COUNT(*) DESC LIMIT 1").fetchall()

[('BRAND', 20)]

BRAND

# Task 3

### Data Quality Issues:

1. Normalization problems
    - composite attribute: '_id' , date columns, 'rewardsReceiptItemList'
      (happens in all 3 tables)
    - multi-value attribute: 'rewardsReceiptItemList'
      (happens in receipts)
      
2. Missing values & Duplicated values
    - Missing values in Primary keys: no
    - But after decomposing receipts.rewardsReceiptItemList into a new data frame, a lot missing values in features.
      This may cause problems in future analysis. 
      Could delete some useless features.
    
    - Duplicated Primary keys: yes
      (happens in users)

# Task 4 Communication

Good morning:

I hope all is well!

I am Xue Han, a Data Analyst from xxx team. After reviewing our data of receipts, users, and brands, I have some questions need to be clarified and also come across some problems regarding to the data quality that need to be fixed:
    
    1. The tables have multi-value and composite attributes, which could be a problem when scaling the data sets.
    2. Since the 'rewardsReceiptItemList' needs to be pulled out as an independent table, we should create a data dictionary for it.
    3. There are lot duplicated records in 'users' table (353 duplicates), I believe we should check the system why this happened.
    4. In the 'receipts' table, all 'createDate' values equal to 'dateScanned' values. Is it possible to remove one feature?
    5. There are a lot missing values in 'rewardsReceiptItemList', which may make the table useless in future analysis. We should reconsider the necessity of these feature's existence.
    
To resolve above concerns, I think we need to confirm our objective of the data and the rationality of the design of the database. If possible, I'd also like to check the meta-data to get a better understanding. 

Please let me know if you have any questions regarding the above. 

Best,

Xue